services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./backend/mongo/initdb:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
