detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeVariableName:
    accept:
      - e
  UnusedParameters:
    enabled: false
  UtilityFunction:
    enabled: false
directories:
  "test":
    FeatureEnvy:
      enabled: false
    NilCheck:
      enabled: false
    UtilityFunction:
      enabled: false
