require:
  - rubocop-rake
  - rubocop-graphql

AllCops:
  NewCops: enable
  Exclude:
    - bin/tapioca
    - bin/console
    - Rakefile

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/FieldDescription:
  Enabled: false
