# frozen_string_literal: true

source "https://rubygems.org"

gem "dry-container"
gem "dry-inflector"
gem "graphql"
gem "jwt"
gem "mongo"
gem "oauth2"
gem "rake"
gem "test-unit"
gem "ulid"
gem "warning"
gem "zeitwerk"

gem "sinatra"
gem "sinatra-contrib"

gem "rack-contrib"
gem "rack-cors"
gem "redis-rack"

group :development do
  gem "rubycritic", require: false

  gem "rubocop", require: false
  gem "rubocop-graphql", require: false
  gem "rubocop-rake", require: false
end

group :test do
  gem "rack-test"
  gem "simplecov", require: false
  gem "test-unit-rr"
end

group :development, :test do
  gem "dotenv", require: false
end
