# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `dry-container` gem.
# Please instead update this file by running `bin/tapioca gem dry-container`.

module Dry; end

class Dry::Container
  include ::Dry::Container::Mixin::Initializer
  include ::Dry::Container::Mixin
  extend ::Dry::Container::Configuration

  def config; end
end

class Dry::Container::Config
  def initialize(namespace_separator: T.unsafe(nil), resolver: T.unsafe(nil), registry: T.unsafe(nil)); end

  def namespace_separator; end
  def namespace_separator=(_arg0); end
  def registry; end
  def registry=(_arg0); end
  def resolver; end
  def resolver=(_arg0); end
end

Dry::Container::Config::DEFAULT_NAMESPACE_SEPARATOR = T.let(T.unsafe(nil), String)
Dry::Container::Config::DEFAULT_REGISTRY = T.let(T.unsafe(nil), Dry::Container::Registry)
Dry::Container::Config::DEFAULT_RESOLVER = T.let(T.unsafe(nil), Dry::Container::Resolver)

module Dry::Container::Configuration
  def config; end
  def configure; end
end

Dry::Container::EMPTY_HASH = T.let(T.unsafe(nil), Hash)
class Dry::Container::Error < ::StandardError; end

class Dry::Container::Item
  def initialize(item, options = T.unsafe(nil)); end

  def call; end
  def callable?; end
  def item; end
  def map(func); end
  def options; end
  def value?; end
end

class Dry::Container::Item::Callable < ::Dry::Container::Item
  def call; end
end

class Dry::Container::Item::Factory
  def call(item, options = T.unsafe(nil)); end
end

class Dry::Container::Item::Memoizable < ::Dry::Container::Item
  def initialize(item, options = T.unsafe(nil)); end

  def call; end
  def memoize_mutex; end

  private

  def raise_not_supported_error; end
end

class Dry::Container::KeyError < ::KeyError; end

module Dry::Container::Mixin
  mixes_in_class_methods ::Dry::Container::Configuration

  def [](key); end
  def _container; end
  def clone; end
  def decorate(key, with: T.unsafe(nil), &block); end
  def dup; end
  def each(&block); end
  def each_key(&block); end
  def enable_stubs!; end
  def freeze; end
  def import(namespace); end
  def key?(key); end
  def keys; end
  def merge(other, namespace: T.unsafe(nil), &block); end
  def namespace(namespace, &block); end
  def register(key, contents = T.unsafe(nil), options = T.unsafe(nil), &block); end
  def resolve(key, &block); end

  class << self
    def extended(base); end
    def included(base); end
  end
end

module Dry::Container::Mixin::Initializer
  def initialize(*args, &block); end
end

class Dry::Container::Namespace
  def initialize(name, &block); end

  def block; end
  def name; end
end

class Dry::Container::NamespaceDSL < ::SimpleDelegator
  def initialize(container, namespace, namespace_separator, &block); end

  def import(namespace); end
  def namespace(namespace, &block); end
  def register(key, *args, &block); end
  def resolve(key); end

  private

  def namespaced(key); end
end

Dry::Container::PREFIX_NAMESPACE = T.let(T.unsafe(nil), Proc)

class Dry::Container::Registry
  def initialize; end

  def call(container, key, item, options); end
  def factory; end
end

class Dry::Container::Resolver
  def call(container, key); end
  def each(container, &block); end
  def each_key(container, &block); end
  def key?(container, key); end
  def keys(container); end
end

module Dry::Container::Stub
  def enable_stubs!; end
  def resolve(key); end
  def stub(key, value, &block); end
  def unstub(*keys); end

  private

  def _stubs; end
end

Dry::Container::VERSION = T.let(T.unsafe(nil), String)
